//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opensource_manager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardActiveUser
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public int CardID { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual ProjectUser ProjectUser { get; set; }
    }
}
