//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opensource_manager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
        public byte[] Attatchment { get; set; }
        public int CardID { get; set; }
        public string CreatorID { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
