//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opensource_manager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventLogId { get; set; }
        public int FK_ProjectId { get; set; }
        public System.DateTime ScrumUpdated { get; set; }
    }
}
